lsst: pin click
Apparently we require click < 8.2, or we get:
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases